networks:
  bridge:

services:
  account:
    build:
      target: account-builder
    command: ["/go/bin/account"]
    environment:
      DB_CONNECTION_STRING: user=postgres password=postgres host=postgres port=5432 dbname=postgres
    ports:
      - 8000:8000
    networks:
      - bridge
    develop:
      watch:
        - action: rebuild
          path: ./account
        - action: rebuild
          path: ./contrib

  postgres:
    image: postgres:17.0-alpine3.20
    restart: always
    environment: 
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./build/postgres:/docker-entrypoint-initdb.d
    networks:
        - bridge

  rabbitmq:
    image: rabbitmq:4.0.2-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /var/lib/rabbitmq
      - /var/log/rabbitmq
    networks:
      - bridge
